name: TEstCacheAction

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # step 1: Checkout repo
      - name: Checkout repositoty
        uses: actions/checkout@v4

      # step 2: setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # step 3: Cache dependencies
      - name: Prime cache 010a330
        id: prime-cache-010a330
        uses: actions/cache@v4
        with:
          path:
            ~/.cache/pip
          key: cache-010a330
      
      # step 4: Show cache hit/miss
      - name: Cache hit/miss result
        run: echo "Cache hit? ${{steps.prime-cache-010a330.outputs.cahce-hit}}"
