name: TestAction

on:
  push:
    branches: [main]

jobs:
  hello:
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: 23f1002487@ds.study.iitm.ac.in
        run: echo "Hello, world!"
